import { build } from 'esbuild';
import { readdir, readFile, mkdir, writeFile, rm, realpath, cp } from 'node:fs/promises';
import { resolve, dirname, relative, join } from 'node:path';

const entries = ['html', 'workbook', 'word', 'epub', 'zip', 'exif', 'ocr'];
const outputDirectory = resolve('extension/vendor');
// Only this generated directory is removed; refuse redirected/symlinked paths.
const existingOutput = await realpath(outputDirectory).catch(() => null);
if (existingOutput && existingOutput.toLowerCase() !== outputDirectory.toLowerCase()) throw new Error('Refusing to clean a redirected vendor directory.');
await rm(outputDirectory, { recursive: true, force: true });
const result = await build({
  entryPoints: Object.fromEntries(entries.map(name => [name, `scripts/vendor/${name}.js`])),
  outdir: 'extension/vendor', bundle: true, splitting: true, format: 'esm', platform: 'browser',
  target: 'chrome130', minify: true, metafile: true, legalComments: 'linked',
  alias: { 'onnxruntime-web': 'onnxruntime-web/wasm' },
  chunkNames: 'chunks/[name]-[hash]', logLevel: 'warning'
});

const runtimeAssets = [];
async function copyAsset(source, destination) {
  await mkdir(dirname(destination), { recursive: true });
  await cp(source, destination, { recursive: true });
  runtimeAssets.push(destination.replace('extension/', ''));
}
for (const name of ['ort-wasm-simd-threaded.mjs', 'ort-wasm-simd-threaded.wasm']) await copyAsset(`node_modules/onnxruntime-web/dist/${name}`, `extension/vendor/ort/${name}`);
for (const name of ['pdf.mjs', 'pdf.worker.mjs']) await copyAsset(`node_modules/pdfjs-dist/legacy/build/${name}`, `extension/vendor/pdf/${name}`);
// PDF.js may finish an empty operator list when a raster resource exceeds its
// configured cap. Expose that specific event to our caller without changing
// parsing, rendering or the cap. Keep this exact patch guarded on upgrades.
const pdfWorkerPath = 'extension/vendor/pdf/pdf.worker.mjs';
const pdfWorkerSource = await readFile(pdfWorkerPath, 'utf8');
const capMarker = 'const msg = "Image exceeded maximum allowed size and was removed.";';
if (pdfWorkerSource.split(capMarker).length !== 2) throw new Error('PDF.js resource-limit diagnostic patch requires review.');
await writeFile(pdfWorkerPath, pdfWorkerSource.replace(capMarker, `${capMarker}\n      globalThis.__markitdownPdfLimit?.(msg);\n      globalThis.postMessage?.({ type: 'markitdown-pdf-limit', message: msg });`));
for (const name of ['cmaps', 'standard_fonts', 'iccs']) await copyAsset(`node_modules/pdfjs-dist/${name}`, `extension/vendor/pdf/${name}`);
// Document JavaScript is never used: do not distribute the optional QuickJS
// evaluator. Copy only image/color decoders and their full notices.
for (const name of (await readdir('node_modules/pdfjs-dist/wasm')).filter(name => !name.startsWith('quickjs-eval'))) await copyAsset(`node_modules/pdfjs-dist/wasm/${name}`, `extension/vendor/pdf/wasm/${name}`);

// Include full upstream licenses for every bundled package, including transitives.
const packageDirs = new Map();
for (const name of ['pdfjs-dist', 'onnxruntime-web', 'onnxruntime-common']) {
  const directory = resolve('node_modules', name);
  packageDirs.set(directory, JSON.parse(await readFile(join(directory, 'package.json'), 'utf8')));
}
for (const file of Object.keys(result.metafile.inputs).filter(file => file.includes('node_modules/'))) {
  let directory = dirname(resolve(file));
  while (directory.includes('node_modules')) {
    try {
      const pkg = JSON.parse(await readFile(join(directory, 'package.json'), 'utf8'));
      if (pkg.name && pkg.version) { packageDirs.set(directory, pkg); break; }
    } catch { /* Continue to the package root. */ }
    directory = dirname(directory);
  }
}
// LinkeDOM's worker entry and JSZip's browser entry are themselves prebundled.
// Their embedded dependencies do not appear separately in esbuild's metafile.
async function includeDependencyLicenses(directory) {
  const pkg = JSON.parse(await readFile(join(directory, 'package.json'), 'utf8'));
  packageDirs.set(directory, pkg);
  for (const name of Object.keys(pkg.dependencies || {})) {
    let parent = directory, found;
    while (parent !== dirname(parent)) {
      const candidate = join(parent, 'node_modules', name);
      try { await readFile(join(candidate, 'package.json')); found = candidate; break; } catch { parent = dirname(parent); }
    }
    if (!found) throw new Error(`Cannot locate license for ${name}`);
    if (!packageDirs.has(found)) await includeDependencyLicenses(found);
  }
}
for (const [directory, pkg] of [...packageDirs]) if (['linkedom', 'jszip'].includes(pkg.name)) await includeDependencyLicenses(directory);
const notices = ['# Third-party notices', '', 'Generated by `npm run build`. JavaScript and WASM are local. Only the pinned OCR model data downloads on first use.', '', 'JSZip is used under its MIT license option. Full upstream notices are retained below.', '', '## PaddleOCR models (Apache-2.0)', '', 'Source: https://github.com/PT-Perkasa-Pilar-Utama/ppu-paddle-ocr-models/tree/384182c7187c12d4ea181ae3b97c8b7e12089d9d', '', await readFile('scripts/vendor/PADDLE_MODELS_LICENSE.txt', 'utf8'), ''];
notices.push('## Local PDF.js modification', '', 'The bundled PDF worker adds a resource-limit diagnostic callback/message when its existing image-size guard rejects an image. This prevents an empty operator list from being reported as a blank-page success. scripts/build.mjs applies the exact guarded patch. The optional QuickJS evaluator is not distributed.', '');
notices.push('## Microsoft MarkItDown attribution', '', 'This independent JavaScript extension ports the document-to-Markdown concept and feature scope of Microsoft MarkItDown. It is not an official Microsoft product. The upstream notice is retained for the acknowledged upstream work.', '', await readFile('scripts/vendor/MICROSOFT_MARKITDOWN_LICENSE.txt', 'utf8'), '');
for (const name of ['ONNX_LICENSE.txt', 'ONNX_ThirdPartyNotices.txt']) notices.push(`## ${name}`, '', await readFile(`scripts/vendor/${name}`, 'utf8'), '');
for (const directory of ['standard_fonts', 'wasm', 'cmaps', 'iccs']) {
  for (const name of (await readdir(`node_modules/pdfjs-dist/${directory}`)).filter(name => /^LICENSE/i.test(name))) notices.push(`## PDF.js ${directory}/${name}`, '', await readFile(`node_modules/pdfjs-dist/${directory}/${name}`, 'utf8'), '');
}
for (const [directory, pkg] of [...packageDirs].sort((a, b) => a[1].name.localeCompare(b[1].name))) {
  notices.push(`## ${pkg.name} ${pkg.version}`, '', `Declared license: ${typeof pkg.license === 'string' ? pkg.license : JSON.stringify(pkg.license || pkg.licenses)}`, '');
  const licenses = (await readdir(directory)).filter(file => /^(licen[cs]e|copying|notice)(\.|$)/i.test(file));
  for (const filename of licenses) notices.push(`### ${filename}`, '', '```text', (await readFile(join(directory, filename), 'utf8')).trim(), '```', '');
  if (!licenses.length) {
    const readme = (await readdir(directory)).find(file => /^readme(?:\.|$)/i.test(file));
    const text = readme ? await readFile(join(directory, readme), 'utf8') : '';
    const section = text.match(/^#{1,3}\s+licen[cs]e\s*$/im);
    if (!section) throw new Error(`License text missing for bundled package ${pkg.name}`);
    notices.push(`### License from ${readme}`, '', text.slice(section.index + section[0].length).trim(), '');
  }
  if (pkg.name === 'pako') {
    const source = await readFile(join(directory, 'lib/zlib/inflate.js'), 'utf8');
    const notice = source.match(/\/\/ \(C\)[\s\S]+?(?=\r?\n\r?\nvar)/)?.[0];
    if (!notice) throw new Error('Missing embedded zlib notice.');
    notices.push('### Embedded zlib notice', '', '```text', notice, '```', '');
  }
}
await writeFile('extension/THIRD_PARTY_NOTICES.md', notices.join('\n'));
await cp('LICENSE', 'extension/LICENSE');
await mkdir('build', { recursive: true });
await writeFile('build/vendor-manifest.json', JSON.stringify({
  packages: [...packageDirs.values()].map(({ name, version, license }) => ({ name, version, license })),
  outputs: [...Object.keys(result.metafile.outputs).map(file => relative(resolve('extension'), resolve(file)).replaceAll('\\', '/')), ...runtimeAssets]
}, null, 2) + '\n');
const bytes = Object.values(result.metafile.outputs).reduce((sum, output) => sum + output.bytes, 0);
console.log(`Bundled ${entries.length} library entry points: ${(bytes / 1024 / 1024).toFixed(2)} MiB plus full license notices.`);
